version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: zagbaz/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: zagbaz/foodgram_frontend:latest
    volumes:
      - frontend_data:/app/build/

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/redoc.html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value:

